FRW-9206: remove debug

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -835,7 +835,7 @@ jobs:
                     APPLICATION_STORE=AT docker/sdk console queue:worker:start --stop-when-empty
             -   name: Run Tests
                 run: |
-                    docker/sdk exec robot-framework robot -v env:api_mp_b2c -v glue_env:http://glue.eur.spryker.local -v yves_env:http://yves.eur.spryker.local -v docker:True --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.mp_b2c .
+                    docker/sdk exec robot-framework robot -v env:api_mp_b2c -v docker:True --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.mp_b2c .
             -   name: Upload artifacts
                 if: failure()
                 run: |
@@ -880,7 +880,7 @@ jobs:
                     docker/sdk console queue:worker:start --stop-when-empty
             -   name: Run Tests
                 run: |
-                    docker/sdk exec robot-framework robot -v env:api_mp_b2c -v db_engine:psycopg2 -v docker:True -v dms:true -v glue_env:http://glue.eur.spryker.local -v bapi_env:http://glue-backend.eu.spryker.local -v sapi_env:http://glue-storefront.eu.spryker.local --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.mp_b2c .
+                    docker/sdk exec robot-framework robot -v env:api_mp_b2c -v db_engine:psycopg2 -v docker:True -v dms:true -v glue_env:http://glue.eu.spryker.local -v bapi_env:http://glue-backend.eu.spryker.local -v sapi_env:http://glue-storefront.eu.spryker.local --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.mp_b2c .
             -   name: Upload artifacts
                 if: failure()
                 run: |
@@ -924,7 +924,7 @@ jobs:
                     docker/sdk console queue:worker:start --stop-when-empty
             -   name: Run Tests
                 run: |
-                    docker/sdk exec robot-framework robot -v env:api_mp_b2c -v docker:True -v dms:true -v glue_env:http://glue.eur.spryker.local -v bapi_env:http://glue-backend.eu.spryker.local -v sapi_env:http://glue-storefront.eu.spryker.local --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.mp_b2c .
+                    docker/sdk exec robot-framework robot -v env:api_mp_b2c -v docker:True -v dms:true -v glue_env:http://glue.eu.spryker.local -v bapi_env:http://glue-backend.eu.spryker.local -v sapi_env:http://glue-storefront.eu.spryker.local --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.mp_b2c .
             -   name: Upload artifacts
                 if: failure()
                 run: |
@@ -972,7 +972,7 @@ jobs:
                 run: |
                     docker/sdk exec cypress-tests cp .env.example .env
                     for i in 1 2; do
-                      docker/sdk exec --env "ENV_REPOSITORY_ID=b2c-mpttt" cypress-tests npm run cy:ci && s=0 && break || s=$? && echo "Test failed, retrying..."
+                      docker/sdk exec --env "ENV_REPOSITORY_ID=b2c-mp" cypress-tests npm run cy:ci && s=0 && break || s=$? && echo "Test failed, retrying..."
                       sleep 1
                     done
                     (exit $s)
@@ -1025,7 +1025,7 @@ jobs:
                 run: |
                     docker/sdk exec cypress-tests cp .env.dynamic-store.example .env
                     for i in 1 2; do
-                      docker/sdk exec --env "ENV_REPOSITORY_ID=b2c-mpttt" cypress-tests npm run cy:ci && s=0 && break || s=$? && echo "Test failed, retrying..."
+                      docker/sdk exec --env "ENV_REPOSITORY_ID=b2c-mp" cypress-tests npm run cy:ci && s=0 && break || s=$? && echo "Test failed, retrying..."
                       sleep 1
                     done
                     (exit $s)
@@ -1073,7 +1073,7 @@ jobs:
                     docker/sdk console queue:worker:start --stop-when-empty
             -   name: Run Tests
                 run: |
-                    docker/sdk exec robot-framework robot -v env:api_mp_b2c -v docker:True -v dms:true -v glue_env:http://glue.eur.spryker.local -v bapi_env:http://glue-backend.eu.spryker.local -v sapi_env:http://glue-storefront.eu.spryker.local --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.mp_b2c.'*'.positive .
+                    docker/sdk exec robot-framework robot -v env:api_mp_b2c -v docker:True -v dms:true -v glue_env:http://glue.eu.spryker.local -v bapi_env:http://glue-backend.eu.spryker.local -v sapi_env:http://glue-storefront.eu.spryker.local --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.mp_b2c.'*'.positive .
             -   name: Upload artifacts
                 if: failure()
                 run: |
@@ -1118,7 +1118,7 @@ jobs:
                     docker/sdk console queue:worker:start --stop-when-empty
             -   name: Run Tests
                 run: |
-                    docker/sdk exec robot-framework robot -v env:api_mp_b2c -v docker:True -v dms:true -v glue_env:http://glue.eur.spryker.local -v bapi_env:http://glue-backend.eu.spryker.local -v sapi_env:http://glue-storefront.eu.spryker.local --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.mp_b2c.'*'.negative .
+                    docker/sdk exec robot-framework robot -v env:api_mp_b2c -v docker:True -v dms:true -v glue_env:http://glue.eu.spryker.local -v bapi_env:http://glue-backend.eu.spryker.local -v sapi_env:http://glue-storefront.eu.spryker.local --exclude skip-due-to-issueORskip-due-to-refactoring -d results -s robotframework.tests.api.mp_b2c.'*'.negative .
             -   name: Upload artifacts
                 if: failure()
                 run: |
