FRW-9206: test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -972,7 +972,7 @@ jobs:
                 run: |
                     docker/sdk exec cypress-tests cp .env.example .env
                     for i in 1 2; do
-                      docker/sdk exec --env "ENV_REPOSITORY_ID=b2c-mp" cypress-tests npm run cy:ci && s=0 && break || s=$? && echo "Test failed, retrying..."
+                      docker/sdk exec --env "ENV_REPOSITORY_ID=b2c-mpttt" cypress-tests npm run cy:ci && s=0 && break || s=$? && echo "Test failed, retrying..."
                       sleep 1
                     done
                     (exit $s)
@@ -1025,7 +1025,7 @@ jobs:
                 run: |
                     docker/sdk exec cypress-tests cp .env.dynamic-store.example .env
                     for i in 1 2; do
-                      docker/sdk exec --env "ENV_REPOSITORY_ID=b2c-mp" cypress-tests npm run cy:ci && s=0 && break || s=$? && echo "Test failed, retrying..."
+                      docker/sdk exec --env "ENV_REPOSITORY_ID=b2c-mpttt" cypress-tests npm run cy:ci && s=0 && break || s=$? && echo "Test failed, retrying..."
                       sleep 1
                     done
                     (exit $s)
